name: Check PR Diffs

on: pull_request

# Reduce ember's parallel-ness to 2,
# the number of cores available on github actions.
# See the following for details:
# https://git.io/vdao3
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
env:
  JOBS: 2

jobs:
  lighthouse:
    name: Generate Lighthouse Score
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install the correct version of node
      - name: Detect Node version
        run: echo "##[set-output name=version;]$(cat .nvmrc)"
        id: nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"

      # Restore yarn cache from between builds
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore dependencies from cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - name: Install dependencies
        run: yarn

      - name: Run Lighthouse
        run: |
          mkdir lhci
          yarn lighthouse
        continue-on-error: true

      - name: Store generated report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lhci
  compare-score:
    name: Compare Lighthouse Score
    runs-on: ubuntu-latest
    needs: lighthouse
    steps:
      - uses: actions/checkout@v2
      - name: Download branch report
        uses: actions/download-artifact
        with:
          name: lighthouse-report
          path: branch-report
      - name: Get latest run ID
        run: |
          echo "::set-env name=LATEST_RUN_URL::(curl \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?branch=master&status=completed" \
            | jq '.workflow_runs[0].url')"
      - name: Get archive download url
        run: |
          echo "::set-env name=DOWNLOAD_URL::(curl \
            "$LATEST_RUN_URL/artifacts" | \
            jq '.artifacts[] | select(.name == "lighthouse-report").archive_download_url'"
      - name: Download archive
        run: |
          curl -v -L \
          -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }} \
          -o master-report.zip \
          $DOWNLOAD_URL
      - name: Extract archive
        run: mkdir master-report && unzip master-report.zip -d master-report
      - name: Christ i hope this works
        run: ls && ls branch-report && ls master-report
